server:
  port: 8085
spring:
  application:
    name: kafka-event-cloud
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: kafka-cloud
      topic-name: kafkacloud.in
      auto-offset-reset: earliest